version: '3.8'

services:
  postgres:
    image: postgres:13.20
    restart: always
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:5
    restart: always
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - '5672:5672'
      - '15672:15672'

  openmusic-api:
    build: .
    restart: on-failure
    env_file:
      - .env
    ports:
      - '5000:5000'
    depends_on:
      - postgres
      - redis
      - rabbitmq
    command: sh -c "npm run migrate up && npm start"

volumes:
  pgdata:
